# ZK EVM Configuration

jumpbox:
  image: leovct/zk_evm_jumpbox:v0.6.0

worker:
  image: leovct/zk_evm:v0.6.0

  # Number of worker pods when autoscaler is disabled.
  workerCount: 4

  autoscaler:
    # Enable or disable the worker autoscaler (HPA).
    enabled: false
    # Minimum number of worker pods to maintain.
    minWorkerCount: 4
    # Maximum number of worker pods to maintain.
    maxWorkerCount: 8
    # Interval (in seconds) for KEDA to check RabbitMQ's queue length and scale worker deployment.
    pollingInterval: 10

  flags:
    # Use the postcard serialization format.
    - --serializer=postcard
    # Use the AMQP runtime environment.
    - --runtime=amqp
    # Persist the processed circuits to disk.
    - --persistence=disk
    # Load all the table circuits into a monolithic bundle.
    - --load-strategy=monolithic

  env:
    # Verbosity level.
    RUST_LOG: info
    # Capture Rust's full backtrace.
    RUST_BACKTRACE: full
    # Set Rust's thread stack size.
    RUST_MIN_STACK: 33554432

    # The min/max size for the arithmetic table circuit.
    ARITHMETIC_CIRCUIT_SIZE: 16..25
    # The min/max size for the byte packing table circuit.
    BYTE_PACKING_CIRCUIT_SIZE: 8..25
    # The min/max size for the cpu table circuit.
    CPU_CIRCUIT_SIZE: 12..27
    # The min/max size for the keccak table circuit.
    KECCAK_CIRCUIT_SIZE: 14..25
    # The min/max size for the keccak sponge table circuit.
    KECCAK_SPONGE_CIRCUIT_SIZE: 9..20
    # The min/max size for the logic table circuit.
    LOGIC_CIRCUIT_SIZE: 12..25
    # The min/max size for the memory table circuit.
    MEMORY_CIRCUIT_SIZE: 17..28

  resources:
    # Resource requests for Kubernetes scheduler.
    requests:
      memory: 24G
      cpu: 5
    # Resource limits enforced by Kubernetes kubelet.
    limits:
      memory: 230G
      cpu: 50

rabbitmq:
  cluster:
    image: rabbitmq:3.13
    # Number of nodes in the RabbitMQ cluster (odd number recommended for fault tolerance).
    nodeCount: 1
    credentials:
      username: guest
      password: guest
